### ISSUE TITLE
undefined: Asset in edi.go

### ISSUE THREAD

**Issue by masukomi** [satran/edi#4]
``` shell
go get github.com/satran/edi
# github.com/satran/edi
workspace/gocode/src/github.com/satran/edi/edi.go:38: undefined: Asset
```

and 

``` shell
go test
# github.com/satran/edi
./edi.go:38: undefined: Asset
```

**Comment by vniche** [comment]
Yep, just ran into that error, searched for it even here on the repo, and the only ref found was the one that complains that it is undefined.

**Comment by satran** [comment]
You need to install go-bindata(http://github.com/jteeuwen/go-bindata). Once you have installed it run INSTALL.sh.

**Comment by vniche** [comment]
Hi satran, having some trouble on that, i run ``go build && go install`` on go-bindata and it doenst generated the binaries on $GOPATH/bin like other projects, about the ``Asset(fileName)`` problem i was able to go through that with ``iotuil.ReadFile(fileName)``, but run into another problem once i got the server up:

``open app/s/c/theme/solarized light.css: no such file or directory``

i think the javascript is trying to access that file, but it doesn't exist, i've even searched for it here on the repo to have sure, confirming me on that, i'll create an issue for it.

**Comment by satran** [comment]
No longer needed. I reworked the application.
